[build]
builder = "nixpacks"
nixpacksConfigPath = "./nixpacks.toml"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.llm_processor.service"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
enabled = true  # Enable the service for deployment

[nixpacks]
python-version = "3.12.1"
