[build]
builder = "nixpacks"
nixpacksConfigPath = "./nixpacks.toml"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.llm_processor.service"
restartPolicyType = "always"
restartPolicyMaxRetries = 10
enabled = false  # LLM processor is disabled by default

[nixpacks]
python-version = "3.12.1"
