[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.llm_processor.service"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3
enabled = true
