[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python -m src.service"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[service]
internal_port = 8000
auto_deploy = true
